# Generated by Django 3.0.4 on 2025-07-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethnic', '0003_country_genre_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('type', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('food', 'Food')], max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethnic.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authentic', models.BooleanField(default=False)),
                ('is_friendly', models.BooleanField(default=False)),
                ('has_alcohol', models.BooleanField(default=False)),
                ('is_clean', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
                ('is_for_girls', models.BooleanField(default=False)),
                ('is_for_family', models.BooleanField(default=False)),
                ('is_luxurious', models.BooleanField(default=False)),
                ('is_unique_food', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethnic.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethnic.Restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='friend',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ethnic.Region'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethnic.PriceRange'),
        ),
    ]
